# Generated by Django 4.2.19 on 2025-03-02 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
