# Generated by Django 4.2.19 on 2025-03-02 19:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_uploadedfile_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
