# Generated by Django 4.2.19 on 2025-03-03 16:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_remove_uploadedfile_uuid_alter_uploadedfile_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('word', models.CharField(max_length=64)),
                ('count', models.IntegerField()),
                ('lemma', models.CharField(max_length=64)),
                ('pos', models.CharField(max_length=8)),
                ('suffixes', models.JSONField(null=True)),
            ],
        ),
    ]
