# Generated by Django 4.2.19 on 2025-03-03 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.uploadedfile'),
            preserve_default=False,
        ),
    ]
