# Generated by Django 4.2.19 on 2025-03-03 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_word_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='tag',
            field=models.CharField(max_length=8),
            preserve_default=False,
        ),
    ]
