# Generated by Django 4.2.19 on 2025-03-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_remove_word_word'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='count',
        ),
        migrations.AddField(
            model_name='word',
            name='word',
            field=models.CharField(max_length=64),
            preserve_default=False,
        ),
    ]
